#!/usr/bin/env python3
"""
AI Summary Generator for FPL Dashboard

Generates roast-style AI summaries using Claude API based on gameweek data.
Uses GW11 summary as a tone reference.

Usage: python generate_ai_summary.py <gameweek>
Example: python generate_ai_summary.py 18
"""

import anthropic
import csv
import os
import sys
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv


def read_summary_data(gameweek: int) -> str:
    """Read the summary markdown file generated by generate_summary.py"""
    summary_file = Path(f"gw{gameweek}") / f"summary_gw{gameweek}.md"

    if not summary_file.exists():
        print(f"❌ Error: {summary_file} not found")
        print(f"   Run: python3 generate_summary.py {gameweek}")
        return None

    # Read the markdown summary
    with open(summary_file, 'r') as f:
        return f.read()


def read_tone_reference() -> str:
    """Read the GW11 AI summary as a tone reference"""
    tone_file = Path("gw11") / "ai_summary_gw11.md"

    if not tone_file.exists():
        print("⚠️  Warning: GW11 tone reference not found, will use default style")
        return None

    with open(tone_file, 'r') as f:
        return f.read()


def generate_ai_summary(gameweek: int, api_key: str) -> str:
    """Generate AI summary using Claude API"""

    # Read summary data
    summary_data = read_summary_data(gameweek)
    if not summary_data:
        return None

    # Read tone reference
    tone_reference = read_tone_reference()

    # Get current date and season info
    current_date = datetime.now()
    current_year = current_date.year
    season = "2025/26"

    # Build the prompt
    if tone_reference:
        prompt = f"""CONTEXT: Today's date is {current_date.strftime('%B %d, %Y')}. We are in the {season} FPL season.

You are writing a savage, hilarious roast-style summary for a Fantasy Premier League Draft league's Gameweek {gameweek}.

CRITICAL TONE REQUIREMENTS:
- Use the EXACT same tone, style, and voice as the reference summary below
- Be absolutely brutal and savage with the roasts
- Use creative insults and metaphors
- Make it funny and entertaining
- Don't hold back - this is all in good fun between friends
- Use emojis sparingly but effectively
- Format with markdown headers for each manager
- Include an intro and conclusion section

REFERENCE SUMMARY (GW11 - use this EXACT tone and style):
{tone_reference}

---

Here is the data for Gameweek {gameweek}:

{summary_data}

Generate a complete roast-style summary for Gameweek {gameweek} following the EXACT same tone, brutality, and style as the reference above. Be creative with new insults but maintain the same energy and voice."""
    else:
        prompt = f"""CONTEXT: Today's date is {current_date.strftime('%B %d, %Y')}. We are in the {season} FPL season.

You are writing a savage, hilarious roast-style summary for a Fantasy Premier League Draft league's Gameweek {gameweek}.

Write a brutally funny roast for each manager based on their performance. Be creative with insults, use metaphors, and make it entertaining. This is all in good fun between friends.

Requirements:
- Start with an intro paragraph summarizing the week
- Roast each manager individually with a markdown header
- Be absolutely savage but creative
- Use emojis sparingly
- End with a conclusion

Here is the data for Gameweek {gameweek}:

{summary_data}

Generate a complete roast-style summary."""

    # Call Claude API
    client = anthropic.Anthropic(api_key=api_key)

    print(f"🤖 Generating AI summary with Claude...")
    print(f"   Using model: claude-opus-4-20250514")

    message = client.messages.create(
        model="claude-opus-4-20250514",
        max_tokens=8192,  # Increased to allow full roast summaries
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return message.content[0].text


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_ai_summary.py <gameweek>")
        print("Example: python generate_ai_summary.py 18")
        sys.exit(1)

    gameweek = int(sys.argv[1])

    print("=" * 80)
    print(f"  AI SUMMARY GENERATOR - GW{gameweek}")
    print("=" * 80)

    # Load environment variables
    load_dotenv()
    api_key = os.getenv('ANTHROPIC_API_KEY')

    if not api_key:
        print("❌ Error: ANTHROPIC_API_KEY not found in .env file")
        print("   Add: ANTHROPIC_API_KEY=sk-ant-api...")
        sys.exit(1)

    # Generate summary
    summary = generate_ai_summary(gameweek, api_key)

    if not summary:
        print("❌ Failed to generate summary")
        sys.exit(1)

    # Save to file
    output_file = Path(f"gw{gameweek}") / f"ai_summary_gw{gameweek}.md"
    with open(output_file, 'w') as f:
        f.write(summary)

    print(f"\n✅ AI summary generated!")
    print(f"📄 Saved to: {output_file}")
    print(f"📊 Length: {len(summary)} characters")
    print(f"\n✨ Preview:")
    print("-" * 80)
    print(summary[:500] + "..." if len(summary) > 500 else summary)
    print("-" * 80)


if __name__ == '__main__':
    main()
